### ISSUE TITLE
Latest release broke our apps merge tag code

### ISSUE THREAD

**Issue by robert-lara** [ardas/stripo-plugin#35]
Last Thursday the use of merge tags broke in our app (after a user selects a merge tag, the tag is no longer applied and throws an error). It specifically broke on the 6th of June which coincided with the following commit.

https://github.com/ardas/stripo-plugin/commit/f4d4a335b2ba2f34c94fdef9f088d467626fe3d5

I don't know if this coincides with a recent release or not since this is the URL we use to get the code from Stripo. I am just wondering if it is possible to roll our endpoint back to before last week? If so what do I do to the url and how can I get the versions available for reference?

https://plugins.stripo.email/static/latest/stripo.js

Here is the error just to make note if it and if anyone else is getting this issue

```
zone-evergreen.js:171 Uncaught TypeError: Cannot read properties of undefined (reading 'list')
    at se (main.6fd4491877fe76d0cd98.js:28:241894)
    at Object.selectCallback (main.6fd4491877fe76d0cd98.js:28:50915)
    at HTMLDivElement.<anonymous> (mergeTags.js:131:1)
    at ZoneDelegate.invokeTask (zone-evergreen.js:399:1)
    at Zone.runTask (zone-evergreen.js:167:1)
    at ZoneTask.invokeTask [as invoke] (zone-evergreen.js:480:1)
    at invokeTask (zone-evergreen.js:1621:1)
    at HTMLDivElement.globalZoneAwareCallback (zone-evergreen.js:1647:1)
```

**Comment by robert-lara** [comment]
Figured it out!

https://plugins.stripo.email/static/rev/1.116.0/stripo.js
